# Generated by Django 3.2.12 on 2022-06-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='content',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='review',
            name='title',
        ),
    ]
